## Encoding Ordinal Data

In [144]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [145]:
df = pd.read_csv("StudentPerformanceFactors.csv")

In [146]:
df.sample(5)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
996,31,96,Medium,Medium,Yes,8,93,Low,Yes,3,Low,Medium,Public,Positive,3,No,High School,Near,Male,75
2877,16,68,Medium,Medium,Yes,7,85,Medium,Yes,1,Medium,Medium,Public,Positive,2,No,College,Near,Female,65
4760,12,71,Medium,Low,No,8,100,Medium,Yes,2,High,Medium,Public,Neutral,3,Yes,College,Near,Male,63
1476,19,77,High,Medium,Yes,6,54,Low,Yes,3,High,Medium,Private,Negative,2,No,College,Moderate,Male,66
1386,28,82,Low,Medium,Yes,5,95,Medium,Yes,0,High,Low,Public,Neutral,3,No,High School,Near,Male,69

In [147]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [148]:
df.shape

(6607, 20)

In [149]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [150]:
df.dropna(subset=["Teacher_Quality","Parental_Education_Level","Distance_from_Home"], inplace=True)

In [151]:
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [152]:
df.duplicated().sum()

np.int64(0)

In [153]:
df["Distance_from_Home"].unique()

array(['Near', 'Moderate', 'Far'], dtype=object)

In [154]:
df["Parental_Education_Level"].unique()

array(['High School', 'College', 'Postgraduate'], dtype=object)

In [155]:
X = df.iloc[:, 16:18]

In [156]:
X

     Parental_Education_Level Distance_from_Home
0                 High School               Near
1                     College           Moderate
2                Postgraduate               Near
3                 High School           Moderate
4                     College               Near
...                       ...                ...
6602              High School               Near
6603              High School               Near
6604             Postgraduate               Near
6605              High School                Far
6606             Postgraduate               Near

[6378 rows x 2 columns]

In [157]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, df.iloc[:, -1], test_size=0.2, random_state=42)

In [158]:
X_train

     Parental_Education_Level Distance_from_Home
2356              High School           Moderate
4758                  College           Moderate
2281              High School           Moderate
485              Postgraduate               Near
4200              High School               Near
...                       ...                ...
3904             Postgraduate               Near
5378              High School               Near
5415             Postgraduate           Moderate
5582                  College               Near
894              Postgraduate                Far

[5102 rows x 2 columns]

In [159]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[["High School", "College", "Postgraduate"], ["Near", "Moderate", "Far"]])

In [160]:
oe.fit(X_train)

OrdinalEncoder(categories=[['High School', 'College', 'Postgraduate'],
                           ['Near', 'Moderate', 'Far']])

In [161]:
oe.transform(X_train)
oe.transform(X_test)

array([[0., 2.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [1., 0.],
       [1., 1.]], shape=(1276, 2))

### ONE HOT Encoding -- Encoding Nominal Data

In [162]:
cars=pd.read_csv("test-data.csv")

In [163]:
cars.sample(2)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
1076,1076,Honda City V MT,Mumbai,2013,80000,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN
180,180,Volkswagen Vento Petrol Comfortline,Mumbai,2013,67000,Petrol,Manual,First,15.04 kmpl,1598 CC,103.6 bhp,5.0,NaN

In [164]:
cars.set_index("Unnamed: 0")

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
Unnamed: 0,,,,,,,,,,,,
0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN
2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh
3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN
4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1229,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN
1230,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN
1231,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN
1232,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN
1233,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN

In [165]:
cars["Location"].unique()

array(['Delhi', 'Coimbatore', 'Mumbai', 'Hyderabad', 'Pune', 'Jaipur',
       'Chennai', 'Kochi', 'Bangalore', 'Kolkata', 'Ahmedabad'],
      dtype=object)

In [166]:
cars.head(2)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN

In [167]:
cars=cars.iloc[:,1:7]

In [168]:
cars.sample(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission
207,Maruti Omni E 8 Str STD,Bangalore,2005,81245,Petrol,Manual
585,Nissan Sunny 2011-2014 Diesel XL,Kolkata,2012,45000,Diesel,Manual

In [169]:
cars["Fuel_Type"].unique()

array(['CNG', 'Petrol', 'Diesel', 'LPG'], dtype=object)

In [170]:
cars["Name"].value_counts()

Name
Maruti Alto LXi                                         9
Volkswagen Polo 1.2 MPI Highline                        8
Maruti Swift Dzire VDI                                  8
Honda City 1.5 V MT                                     8
Maruti Alto 800 2016-2019 LXI                           7
                                                       ..
Hyundai Verna 1.6 SX VTVT (O)                           1
Hyundai Elite i20 Magna Plus                            1
Honda Amaze VX AT i-Vtech                               1
Chevrolet Aveo 1.4 LS                                   1
Mercedes-Benz E-Class 2009-2013 E 220 CDI Avantgarde    1
Name: count, Length: 768, dtype: int64

In [171]:
cars['brand'] = cars['Name'].str.split().str[0]

In [172]:
cars.drop("Name", axis=1, inplace=True)

In [173]:
cars.head()

     Location  Year  Kilometers_Driven Fuel_Type Transmission    brand
0       Delhi  2014              40929       CNG       Manual   Maruti
1  Coimbatore  2013              54493    Petrol       Manual   Maruti
2      Mumbai  2017              34000    Diesel       Manual   Toyota
3   Hyderabad  2012             139000    Diesel       Manual   Toyota
4      Mumbai  2014              29000    Petrol       Manual  Hyundai

In [174]:
cars["brand"].unique()

array(['Maruti', 'Toyota', 'Hyundai', 'Mahindra', 'Honda', 'Audi',
       'Nissan', 'BMW', 'Ford', 'Skoda', 'Volkswagen', 'Mitsubishi',
       'Mercedes-Benz', 'Tata', 'Chevrolet', 'Datsun', 'Jaguar', 'Fiat',
       'Hindustan', 'Renault', 'Mini', 'Bentley', 'Land', 'Volvo',
       'Isuzu', 'Jeep', 'Porsche', 'ISUZU', 'OpelCorsa'], dtype=object)

In [175]:
cars["brand"]=cars["brand"].replace("ISUZU","Isuzu")

In [176]:
cars["brand"].value_counts()

brand
Maruti           233
Hyundai          233
Honda            135
Toyota            96
Mercedes-Benz     62
Mahindra          59
Volkswagen        59
Ford              51
Audi              49
BMW               45
Tata              42
Chevrolet         30
Skoda             29
Nissan            26
Renault           25
Fiat              10
Mitsubishi         9
Jaguar             8
Land               7
Volvo              7
Mini               5
Datsun             4
Jeep               4
Isuzu              2
Hindustan          1
Bentley            1
Porsche            1
OpelCorsa          1
Name: count, dtype: int64

In [177]:
cars["Transmission"].value_counts()

Transmission
Manual       905
Automatic    329
Name: count, dtype: int64

In [178]:
cars["Location"].value_counts()

Location
Mumbai        159
Pune          143
Coimbatore    136
Hyderabad     134
Kochi         121
Kolkata       119
Delhi         106
Chennai        97
Jaipur         86
Bangalore      82
Ahmedabad      51
Name: count, dtype: int64

### 1. ONE-HOT Encoding using Pandas

In [179]:
pd.get_dummies(cars, columns=["Fuel_Type", "Transmission"], dtype=int)

,Location,Year,Kilometers_Driven,brand,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Delhi,2014,40929,Maruti,1,0,0,0,0,1
1,Coimbatore,2013,54493,Maruti,0,0,0,1,0,1
2,Mumbai,2017,34000,Toyota,0,1,0,0,0,1
3,Hyderabad,2012,139000,Toyota,0,1,0,0,0,1
4,Mumbai,2014,29000,Hyundai,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
1229,Hyderabad,2011,89411,Volkswagen,0,1,0,0,0,1
1230,Mumbai,2015,59000,Volkswagen,0,0,0,1,1,0
1231,Kolkata,2012,28000,Nissan,0,1,0,0,0,1
1232,Pune,2013,52262,Volkswagen,0,0,0,1,1,0
1233,Kochi,2014,72443,Mercedes-Benz,0,1,0,0,1,0

### 2. K-1 Encoding

In [180]:
pd.get_dummies(cars, columns=["Fuel_Type", "Transmission"], dtype=int, drop_first=True)

,Location,Year,Kilometers_Driven,brand,Fuel_Type_Diesel,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Manual
0,Delhi,2014,40929,Maruti,0,0,0,1
1,Coimbatore,2013,54493,Maruti,0,0,1,1
2,Mumbai,2017,34000,Toyota,1,0,0,1
3,Hyderabad,2012,139000,Toyota,1,0,0,1
4,Mumbai,2014,29000,Hyundai,0,0,1,1
...,...,...,...,...,...,...,...,...
1229,Hyderabad,2011,89411,Volkswagen,1,0,0,1
1230,Mumbai,2015,59000,Volkswagen,0,0,1,0
1231,Kolkata,2012,28000,Nissan,1,0,0,1
1232,Pune,2013,52262,Volkswagen,0,0,1,0
1233,Kochi,2014,72443,Mercedes-Benz,1,0,0,0

In [187]:
cars

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,brand
0,Delhi,2014,40929,CNG,Manual,Maruti
1,Coimbatore,2013,54493,Petrol,Manual,Maruti
2,Mumbai,2017,34000,Diesel,Manual,Toyota
3,Hyderabad,2012,139000,Diesel,Manual,Toyota
4,Mumbai,2014,29000,Petrol,Manual,Hyundai
...,...,...,...,...,...,...
1229,Hyderabad,2011,89411,Diesel,Manual,Volkswagen
1230,Mumbai,2015,59000,Petrol,Automatic,Volkswagen
1231,Kolkata,2012,28000,Diesel,Manual,Nissan
1232,Pune,2013,52262,Petrol,Automatic,Volkswagen
1233,Kochi,2014,72443,Diesel,Automatic,Mercedes-Benz

### 3. ONE HOT Encoding using Sklearn

In [182]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(cars.iloc[:,3:5], cars.iloc[:, 0], test_size = 0.3, random_state=42)

In [183]:
X_train

     Fuel_Type Transmission
362     Diesel       Manual
237     Diesel       Manual
532     Diesel       Manual
2       Diesel       Manual
6       Diesel    Automatic
...        ...          ...
1044    Petrol       Manual
1095    Diesel    Automatic
1130    Diesel       Manual
860     Petrol       Manual
1126    Petrol       Manual

[863 rows x 2 columns]

In [184]:
y_train

362     Bangalore
237     Hyderabad
532     Bangalore
2          Mumbai
6            Pune
          ...
1044       Mumbai
1095    Bangalore
1130       Mumbai
860          Pune
1126      Kolkata
Name: Location, Length: 863, dtype: object

In [185]:
from sklearn.preprocessing import OneHotEncoder

In [195]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [196]:
cars

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,brand
0,Delhi,2014,40929,CNG,Manual,Maruti
1,Coimbatore,2013,54493,Petrol,Manual,Maruti
2,Mumbai,2017,34000,Diesel,Manual,Toyota
3,Hyderabad,2012,139000,Diesel,Manual,Toyota
4,Mumbai,2014,29000,Petrol,Manual,Hyundai
...,...,...,...,...,...,...
1229,Hyderabad,2011,89411,Diesel,Manual,Volkswagen
1230,Mumbai,2015,59000,Petrol,Automatic,Volkswagen
1231,Kolkata,2012,28000,Diesel,Manual,Nissan
1232,Pune,2013,52262,Petrol,Automatic,Volkswagen
1233,Kochi,2014,72443,Diesel,Automatic,Mercedes-Benz

In [197]:
X_train

     Fuel_Type Transmission
362     Diesel       Manual
237     Diesel       Manual
532     Diesel       Manual
2       Diesel       Manual
6       Diesel    Automatic
...        ...          ...
1044    Petrol       Manual
1095    Diesel    Automatic
1130    Diesel       Manual
860     Petrol       Manual
1126    Petrol       Manual

[863 rows x 2 columns]

In [199]:
X_train_new=ohe.fit_transform(X_train[['Fuel_Type','Transmission']])

In [200]:
X_test_new=ohe.fit_transform(X_test[['Fuel_Type','Transmission']])

In [201]:
X_train_new.shape

(863, 4)

### 4. ONE-HOT Encoding with Top categories

In [211]:
counts = cars['brand'].value_counts()

In [212]:
cars['brand'].nunique()

28

In [213]:
threshold=42

In [216]:
repl=counts[counts >= threshold].index

In [223]:
pd.get_dummies(cars['brand'].replace(repl, "uncommon"),dtype='int', drop_first=True).sample(10)

,Chevrolet,Datsun,Fiat,Hindustan,Isuzu,Jaguar,Jeep,Land,Mini,Mitsubishi,Nissan,OpelCorsa,Porsche,Renault,Skoda,Volvo,uncommon
143,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
318,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
291,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
310,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
367,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
264,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1166,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
642,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1139,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1